### ISSUE TITLE
Characters in reference name

### ISSUE THREAD

**Issue by alfredoivan** [combogenomics/CONTIGuator#11]
Hello.
I've had a rare error regarding the character '|' (vertical bar).

When i put my reference.fasta file with that character on the fasta header (single fasta), it wouldn't work.
I had to take out the bar and change it with something else to work.

I tried to trace the error and believe it has to do with makeblastdb, but i'm not sure.

**Comment by esdpoort** [comment]
Hello,

I have a similar problem as the one described above, although not regarding the pipe character.

When the header of my reference fasta file is '>CP000151.1', CONTIGuator tells me 'No contigs mapped to the reference ...' but when I change the header to '>CP000151' (just removing the trailing '.1') it runs perfectly.

I narrowed it down to the GetQueryCoverageAgainstDB function, where the for loop line 1240 is never entered when the trailing '.1' is present.

Was easily fixed for me by removing the '.1' from my fasta headers, but still thought I should mention it here since many fasta files downloaded from ncbi have these trailing '.1' in their headers.
